'use strict';
// Generated by scripts/gen-entries.js from Annex A of proton-install-core-spec.md.
// Never hand-edit; regenerate with:
//   node scripts/gen-entries.js <path-to-proton-install-core-spec.md> > src/linux/entries.js
// source: proton-install-core-spec.md
// source_sha256: fb218afb4a81e3c62fcbddacffb0ed6a733cd75f1e1ae7cee580eeb0b09fecbb
//
// Entry A1's fields, the placement table as { member, placedAs, sha256, bytes, source } rows,
// `placedAs` relative to the executable folder, `source` one of 'archive', 'release' or the
// URL a file is read from, and the archive members the ensure step never extracts. Read by
// routeGate, ensureEntry and installEntry, the three Annex D hooks proton-install-core~9~4,
// ~10~7, ~16~2 and ~33~3 govern. Every entry, and every array and object it carries, is
// deep-frozen: no in-process code may rewrite a digest, a URL or a byte count before
// linux.ensureEntry( or linux.installEntry( reads it.

const deepFreeze = (value) => {
  if (value && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const key of Object.getOwnPropertyNames(value)) deepFreeze(value[key]);
  }
  return value;
};

const entries = deepFreeze([
  {
    "id": "A1",
    "route": "optiscaler",
    "api": "dxgi",
    "apiLabel": "DirectX 12",
    "bitness": 64,
    "emulator": "none",
    "nativeDlss": true,
    "proxy": "dxgi.dll",
    "archive": "OptiScaler_v10.0.0-pre1_20260906.7z",
    "build": "7b7220bb",
    "sha256": "206c52cd59d6108f012968f00a492d049c78e77ad2e850eb7770ad8c29c444dd",
    "bytes": 56063759,
    "url": "https://github.com/y4my4my4m/OptiScaler_DLSSNR_Multipass_MFG/releases/download/nightly/OptiScaler_v10.0.0-pre1_20260906.7z",
    "licence": "GPL-3.0",
    "launchOptions": "none",
    "placement": [
      {
        "member": "OptiScaler.dll",
        "placedAs": "dxgi.dll",
        "sha256": "d9722d1e462d8e7b1972614ff67243c7e4d08c8fd11a2564385a5603449b0ee8",
        "bytes": 25911296,
        "source": "archive"
      },
      {
        "member": "nvngx.dll_dlssnr.dll",
        "placedAs": "nvngx.dll_dlssnr.dll",
        "sha256": "52b2fcef95b0046497da07d192749d908dc855ca4cb46623ac339f18a64cf9db",
        "bytes": 114688,
        "source": "archive"
      },
      {
        "member": "OptiScaler/amd_fidelityfx_framegeneration_dx12.dll",
        "placedAs": "OptiScaler/amd_fidelityfx_framegeneration_dx12.dll",
        "sha256": "02297beedd285e822d3a64f314cf00faf378dcec0edc47ff0c4dd71b3a8c2f18",
        "bytes": 40085776,
        "source": "archive"
      },
      {
        "member": "OptiScaler/amd_fidelityfx_loader_dx12.dll",
        "placedAs": "OptiScaler/amd_fidelityfx_loader_dx12.dll",
        "sha256": "e2d85aa05a9bd9ed8b38935fdf5199372cca6f74c12015143bb6f945ee1608aa",
        "bytes": 26376,
        "source": "archive"
      },
      {
        "member": "OptiScaler/amd_fidelityfx_upscaler_dx12.dll",
        "placedAs": "OptiScaler/amd_fidelityfx_upscaler_dx12.dll",
        "sha256": "d0dcccc74a43c44ba435b7a369b456e0970d8a4464e4bd683119b374f2c9fb46",
        "bytes": 28761864,
        "source": "archive"
      },
      {
        "member": "OptiScaler/amd_fidelityfx_vk.dll",
        "placedAs": "OptiScaler/amd_fidelityfx_vk.dll",
        "sha256": "a1624cc4238fef046f30c4d80ce3f47be63fc5f5373f49e3ee9edb9960f54c78",
        "bytes": 9332432,
        "source": "archive"
      },
      {
        "member": "OptiScaler/libxess.dll",
        "placedAs": "OptiScaler/libxess.dll",
        "sha256": "251659dd84a3e84de67c886a4186e01f3eca49b00641906fe38bb6b807e5d5b7",
        "bytes": 77795704,
        "source": "archive"
      },
      {
        "member": "OptiScaler/libxess_dx11.dll",
        "placedAs": "OptiScaler/libxess_dx11.dll",
        "sha256": "c7cfe86f0c9d94e4fb3696d3cd5035e2bbb6a8b1b0572f8b7395a4cdfd0c625e",
        "bytes": 156016,
        "source": "archive"
      },
      {
        "member": "OptiScaler/libxess_fg.dll",
        "placedAs": "OptiScaler/libxess_fg.dll",
        "sha256": "ec5e0c65e075570c6ede72618bb666d0be0c2e10b2ea9762c0fe8cb8e375ab27",
        "bytes": 22957432,
        "source": "archive"
      },
      {
        "member": "OptiScaler/libxell.dll",
        "placedAs": "OptiScaler/libxell.dll",
        "sha256": "d2030dcd694fda8f2ec7e044b13e6db8f0b56d4ba9113a5efad334e3f3ded8c7",
        "bytes": 415368,
        "source": "archive"
      },
      {
        "member": "Licenses/DirectX_LICENSE.txt",
        "placedAs": "OptiScaler/licenses/DirectX_LICENSE.txt",
        "sha256": "5239850894610071566f7ecee0b751fde43c862032d92b99d7d0f596b3433ebd",
        "bytes": 13147,
        "source": "archive"
      },
      {
        "member": "Licenses/FidelityFX_v2_LICENSE.md",
        "placedAs": "OptiScaler/licenses/FidelityFX_v2_LICENSE.md",
        "sha256": "f0da09d71ad5c82759a179e774535d4a829e5c96c49294167c1152402b2cb400",
        "bytes": 61784,
        "source": "archive"
      },
      {
        "member": "Licenses/RenoDX_ATTRIBUTION.txt",
        "placedAs": "OptiScaler/licenses/RenoDX_ATTRIBUTION.txt",
        "sha256": "1d2f2b2f8cf5c9acfe2eaaa2d2c22face87bd19f7df85453079a28e7123ae727",
        "bytes": 2976,
        "source": "archive"
      },
      {
        "member": "Licenses/XeSS_LICENSE.txt",
        "placedAs": "OptiScaler/licenses/XeSS_LICENSE.txt",
        "sha256": "784be42c39a4a4d03cf85d88e15e59d75828fca773ce45b8dbfffbd7eaf208df",
        "bytes": 4194,
        "source": "archive"
      },
      {
        "member": "LICENSE.GPL-3.0.txt",
        "placedAs": "OptiScaler/licenses/LICENSE.GPL-3.0.txt",
        "sha256": "3972dc9744f6499f0f9b2dbf76696f2ae7ad8af9b23dde66d6af86c9dfb36986",
        "bytes": 35149,
        "source": "https://raw.githubusercontent.com/y4my4my4m/OptiScaler_DLSSNR_Multipass_MFG/7b7220bbb4994a9c8ae60cfc75a44cb67995efb8/LICENSE"
      },
      {
        "member": "OptiScaler.ini",
        "placedAs": "OptiScaler.ini",
        "sha256": "55805050c9ee0a700ece66d9b1ecbe823055712c919f0df85892b326f6ffaed4",
        "bytes": 62675,
        "source": "archive"
      },
      {
        "member": "nvngx_dlssnr.dll",
        "placedAs": "nvngx_dlssnr.dll",
        "sha256": "8270b350cd82de5ce89806872cdd6b6a9249b80836b91bbeb3573470744cc206",
        "bytes": 165840496,
        "source": "release",
        "fileVersion": "310.8.0.0"
      },
      {
        "member": "d3dcompiler_47.dll",
        "placedAs": "d3dcompiler_47.dll",
        "sha256": "af7b99be1b8770c0e4d18e43b04e81d11bdeb667fa6b07ade7a88f4c5676bf9a",
        "bytes": 4916728,
        "source": "release",
        "fileVersion": "10.0.22621.2428"
      }
    ],
    "notExtracted": [
      "OptiScaler/D3D12_OptiScaler/D3D12Core.dll",
      "nvngx.dll_dlssnr.exp",
      "nvngx.dll_dlssnr.lib",
      "nvngx.dll_dlssnr.pdb",
      "setup_linux.sh",
      "setup_windows.bat"
    ]
  }
]);

/** The entry for a route, or undefined where Annex A lists none. */
function entryFor(route) {
  return entries.find((entry) => entry.route === route);
}

/** The placement rows the ensure step extracts from the entry's archive. */
function archiveMembers(entry) {
  return entry.placement.filter((row) => row.source === 'archive');
}

module.exports = { entries, entryFor, archiveMembers };
